vulnerability-management
spinningrachel/XMCyber pull request #3
Opened 2020-12-16 11:44 UTC by Quadrisheriff

The article is not complete, you haven't added the devices, patches, and request sections yet. However, I have added the required screenshots and also edited some parts of the article that are available now.

2020-12-18 08:54 UTC, spinningrachel requested changes

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +The **Vulnerability Management** module displays information about the vulnerabilities affecting your system from multiple perspectives. This module allows you to view your XM Cyber sensors in a layo
```suggestion
The **Vulnerability Management** module displays information about the vulnerabilities affecting your system. Use this module to view data about your network, to review the vulnerability assessments resulting from the scenarios you're running and to understand how to remediate and mitigate these vulneabilities for your Windows devices.
```

@Quadrisheriff have you read the guidelines in the style guide I shared with you?

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +- The patches that will remediate vulnerabilities, and details about those patches including which vulnerabilities each fixes.
```suggestion
- The patches that remediate these vulnerabilities, and details about those patches including which vulnerabilities each of them fixes.
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +The overview and details provided by this module help you to prioritize vulnerabilities so you can easily focus on and fix the most urgent vulnerabilities and the most vulnerable devices with the mos
```suggestion
The overview and details provided by this module help you to prioritize vulnerabilities so you can easily focus on and fix the most urgent vulnerabilities and the most vulnerable devices by using the most comprehensive patches. 
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +To navigate to the **Vulnerabilities Management** module, click ![icvulnerability](../../assets/images/icvulnerability.png) from the navigation panel. The default **Overview** tab is displayed with a
```suggestion
Click ![icvulnerability](../../assets/images/icvulnerability.png) from the navigation panel to navigate to the **Vulnerabilities Management** module. The default **Overview** tab is displayed with an overview of the vulnerabilities in your system similar to the following image:
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +<img src="..\..\assets\images\vulnerabilitiesoverview.png" alt="vulnerability overview" style="zoom:100%;" />
delete this

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +The Overview tab displays an overview of the current status of your scenarios, including a summary of:
```suggestion
The Overview tab appears similar to the following: 
<img src="..\..\assets\images\vulnerabilitiesoverview.png" alt="vulnerability overview" style="zoom:100%;" />

This tab displays an overview of the current status of your scenarios, including a summary of:
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +- The vulnerabilities not yet handled - divided by severity, and how many vulnerabilities have been in the network for the indicated periods of time (in days) (based on the information in the Vulnera
```suggestion
- Vulnerabilities not yet handled - divided by severity, and how many vulnerabilities have been in the network for the indicated periods of time (in days) (based on the information in the Vulnerabilities tab).
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +To gain an insight on a certain summary or status:
```suggestion
To gain insights on a certain summary or status:
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +The Vulnerabilities tab displays all of the vulnerabilities that were found in your network in any of your scenarios, organized per vulnerability. The table appears similar to the following example:
```suggestion
The Vulnerabilities tab displays all of the vulnerabilities that were found in your network based on any of the campaigns that have run. The list is organized per vulnerability. The table appears similar to the following example:
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +To sort and filer your vulnerabilities data:
```suggestion
To sort and filer vulnerability data:
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +-   Click any column. Press <img src="..\..\assets\images\sortup.png" alt="sort up" style="zoom:60%;" /> or <img src="..\..\assets\images\sortdown.png" alt="sort down" style="zoom:60%;" /> to sort th
```suggestion
1. Click any column. 
2. Click <img src="..\..\assets\images\sortup.png" alt="sort up" style="zoom:60%;" /> or <img src="..\..\assets\images\sortdown.png" alt="sort down" style="zoom:60%;" /> to sort the entire table by that column.
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +-   Click <img src="..\..\assets\images\star.png" alt="star" style="zoom:60%;" /> to
@Quadrisheriff something's missing here.

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +**Note -- The data of hidden columns are still displayed during filtering**
```suggestion
**Note -- Data in hidden columns is displayed even when filtered.**
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +To download your vulnerabilities data:
```suggestion
To download vulnerability data:
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +- The data for the selected rows will be exported when one or more rows are selected.
```suggestion
- Data is exported when at least one row is selected.
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +- The data for all of the rows in the system will be exported when no rows are selected.
```suggestion
- When no rows are selected, all of the data the system is exported.
```

2020-12-18 08:54 UTC, spinningrachel commented on _docs/vulnerabilitymanagement.md
> +Often times, the vulnerabilities are fixed with shared patches, as in the above example. This makes the overall picture clearer, and easier to prioritize which vulnerabilities should be handled first
```suggestion
Often times, the vulnerabilities are fixed with shared patches, as in the above example. This makes the overall picture clearer. In this way, it is then easier to prioritize which vulnerabilities that should be handled first.
```

2020-12-18 13:08 UTC, Quadrisheriff commented on _docs/vulnerabilitymanagement.md
> +-   Click <img src="..\..\assets\images\star.png" alt="star" style="zoom:60%;" /> to
The description was not in the original article

2020-12-20 07:15 UTC, spinningrachel approved these changes

2020-12-20 07:18 UTC, merged